language: node_js
node_js:
  - 14.8.0

- name: npm test:ci
      run: npm run test:ci
      env:
         CI: false

cache:
  npm: true
  directories:
    - node_modules
    
install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GIT_TOK
  local_dir: build
  on:
    branch: main
